### ISSUE TITLE
Running client and server separately

### ISSUE THREAD

**Issue by jayavanth** [google/hintless_pir#11]
Hello, is there a way currently to run the client and server as separate processes over a network? If not, is it easy to do that?

**Comment by b5li** [comment]
Yes, you can instantiate `hintless_pir::hintless_simplepir::Server` and `hintless_pir::hintless_simplepir::Client` in separate processes. The interface of these two are fairly simple, and for communication the client would just need to send `HintlessPirRequest` to the server, and the server would send `HintlessPirResponse` back to the client.

**Comment by jayavanth** [comment]
Do I have to handle serialization and deserialization myself?

**Comment by jayavanth** [comment]
ok I was able to do the serialization and deserialization
