### ISSUE TITLE
db_rows x db_cols return 0 for dimensions 65536 x 65536

### ISSUE THREAD

**Issue by Janmajayamall** [google/hintless_pir#5]
When db_rows x db_cols are set to 65536 x 65536, the product returns zero because `int` does not fits the product. A way to fix this will be declare db_rows/db_cols as`int64_t` instead of `int`.

**Comment by b5li** [comment]
Thanks for reporting the issue! This will be fixed in the next commit.

**Comment by b5li** [comment]
This has been fixed now in #6.
