### ISSUE TITLE
Difference between tests hintless_simplepir_benchmark and hintless_simplepir_test 

### ISSUE THREAD

**Issue by jayavanth** [google/hintless_pir#7]
They look quite similar but the latter takes ~200s on my computer while the benchmark only takes 0.1s. Which function is taking so  long to run on the benchmark?

I'm just curious about the query time

**Comment by b5li** [comment]
Yes, both hintless_simplepir_test and hintless_simplepir_benchmarks run the protocol end-to-end, so they look similar. The latter benchmarks the query time, and I would guess the 0.1s time you saw is from the benchmark output. The former reports the entire end-to-end time, from setting up and preprocessing the database (which is a bit expensive but is a one-time cost) to process a request. It may help to compile the test using `-c opt` to enable compiler optimization flags. Plus, the default database parameters in the two are different.

**Comment by jayavanth** [comment]
Thanks @b5li but I'm still a bit confused. I changed the db size to 32768x32768 and the run time for the benchmark is still around 0.1-0.2s. Here's how I'm running it

```
./bazelisk-linux-amd64 run -c opt //hintless_simplepir:hintless_simplepir_benchmarks
INFO: Analyzed target //hintless_simplepir:hintless_simplepir_benchmarks (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //hintless_simplepir:hintless_simplepir_benchmarks up-to-date:
  bazel-bin/hintless_simplepir/hintless_simplepir_benchmarks
INFO: Elapsed time: 0.153s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh hintless_simplepir/hintless_simplepir_benchmarks
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //hintless_simplepir:hintless_simplepir_benchmarks
-----------------------------------------------------------------------------
```

Am I doing something wrong? I wanted to see how the query time varies with db size and other parameters

**Comment by jayavanth** [comment]
Also noticed that the benchmark is run on this function `void BM_HintlessPirRlwe64(benchmark::State& state)` and that includes database setup, preprocessing etc.

**Comment by b5li** [comment]
Benchmarks require explicit `--benchmark_filter` argument, e.g.
`./bazelisk-linux-amd64 run -c opt //hintless_simplepir:hintless_simplepir_benchmarks -- --benchmark_filter=all`

**Comment by jayavanth** [comment]
Thank you! Yes I just wasn't running it right. The query times seem to match
