### ISSUE TITLE
Easy way to view database records

### ISSUE THREAD

**Issue by jayavanth** [google/hintless_pir#9]
Hello, is there an easy way to view database records?

When I try to print them, I get invisible characters on my stdout

```

  for (int i = 0; i <= 100; ++i) {
    if (database->Record(i).ok())
    {
      std::cout<< *database->Record(i)  << std::endl;
    }
  }
```
here I only see invisible characters on the terminal

**Comment by b5li** [comment]
Database records are stored as is with a C char array-like interface. Maybe you can use e.g. `std::hex` to print their HEX representation.

**Comment by jayavanth** [comment]
thanks! that worked
